// DIVA 2.0 — Kooij & Francken, 2010, DIVA Foundation
// All symptom criteria, examples, and impairment domains

export const INATTENTION = [
  { id:"A1", q:"Avez-vous souvent du mal à prêter attention aux détails, ou faites-vous souvent des erreurs d'étourderie dans votre travail ou dans d'autres activités ?",
    adult:["Fait des erreurs d'étourderie","Travaille lentement pour éviter les erreurs","Ne lit pas les instructions avec soin","Du mal à travailler de façon minutieuse","Besoin de trop de temps pour mener à leur terme des tâches complexes","Facilement empêtré par les détails","Travaille trop rapidement et commet ainsi des erreurs"],
    child:["Erreurs d'étourderie lors du travail scolaire","Erreurs parce qu'il ne lisait pas les questions correctement","Ne répondait pas à des questions parce qu'il ne les lisait pas correctement","Ne répondait pas aux questions posées au verso d'un examen","Les autres faisaient remarquer que le travail n'était pas soigné","Ne vérifiait pas ses réponses dans les devoirs scolaires","Besoin de trop de temps pour mener à leur terme des tâches minutieuses"]},
  { id:"A2", q:"Trouvez-vous souvent difficile de soutenir votre attention sur une tâche ?",
    adult:["Incapable de maintenir son attention sur des tâches pendant longtemps","Facilement distrait par ses propres pensées ou associations d'idées","Difficile de suivre un film jusqu'à la fin, ou de lire un livre","Rapidement ennuyé par les choses","Pose des questions sur des sujets déjà discutés"],
    child:["Du mal à maintenir l'attention lors du travail scolaire","Du mal à maintenir l'attention sur un jeu","Facilement distrait","Du mal à se concentrer","Besoin d'un environnement structuré pour ne pas être distrait","Rapidement ennuyé dans des activités"]},
  { id:"A3", q:"Donnez-vous souvent l'impression de ne pas écouter lorsqu'on vous parle directement ?",
    adult:["Rêveur ou préoccupé","Du mal à se concentrer pendant une conversation","Après-coup, ne se rappelle pas du sujet d'une conversation","Change souvent de sujet dans une conversation","D'autres personnes vous disent que vos pensées sont ailleurs"],
    child:["Ne sait plus ce que les parents/enseignants ont dit","Rêveur ou préoccupé","N'écoute qu'avec un contact visuel ou lorsque le ton est élevé","Doit souvent être interpelé","Les questions doivent être répétées"]},
  { id:"A4", q:"Avez-vous souvent du mal à vous conformer aux consignes et à mener à terme vos tâches domestiques ou vos obligations professionnelles ?",
    adult:["Fait plusieurs tâches en même temps sans les terminer","Du mal à finir les tâches une fois que la nouveauté a diminué","Besoin de fixer un délai pour terminer les tâches","Du mal à terminer les tâches administratives","Du mal à suivre les instructions dans un manuel"],
    child:["Du mal à suivre les instructions","En difficulté lorsque les tâches comprennent plusieurs étapes successives","Ne termine pas les choses","Ne termine pas les devoirs ou ne les rend pas","Besoin d'un environnement structuré pour pouvoir terminer les tâches"]},
  { id:"A5", q:"Trouvez-vous souvent difficile d'organiser les tâches ou les activités ?",
    adult:["Du mal à planifier les activités de la vie quotidienne","La maison ou l'espace de travail est en désordre","Planifie trop de tâches ou planification inefficace","Prévoit régulièrement de faire plusieurs choses au même moment","Arrive en retard","Incapable d'utiliser un agenda de manière efficace","Rigide par nécessité de coller au programme","Faible conscience du temps","Établit des listes sans les utiliser","Besoin qu'un tiers structure les choses"],
    child:["Du mal à être prêt à temps","Chambre ou bureau en désordre","Du mal à jouer seul","Du mal à planifier des tâches ou ses devoirs","Fait les choses de manière confuse","Arrive en retard","Faible conscience du temps","Du mal à s'occuper seul"]},
  { id:"A6", q:"Évitez-vous souvent les tâches qui nécessitent un effort mental soutenu ?",
    adult:["Fait en premier les choses les plus faciles ou les plus agréables","Remet à plus tard les tâches ennuyeuses ou difficiles","Remet à plus tard les choses jusqu'à dépasser les délais","Évite les tâches monotones, comme les tâches administratives","N'aime pas lire à cause de l'effort mental","Évite des tâches qui demandent beaucoup de concentration"],
    child:["Évite des devoirs ou aversion pour les devoirs","Lit peu de livres ou n'aime pas lire à cause de l'effort mental","Évite des tâches qui demandent beaucoup de concentration","Déteste les sujets scolaires qui demandent beaucoup de concentration","Remet à plus tard les tâches ennuyeuses ou difficiles"]},
  { id:"A7", q:"Perdez-vous souvent les objets nécessaires à votre travail ou vos activités ?",
    adult:["Égare portefeuille, clés, ou agenda","Oublie des choses en quittant un lieu","Perd des papiers pour son travail","Perd beaucoup de temps à chercher des choses","Panique si des gens ont changé des choses de place","Range les choses au mauvais endroit","Perd des notes, listes ou numéros de téléphone"],
    child:["Perd l'agenda, les stylos, les affaires de gymnastique ou d'autres choses","Égare des jouets, habits ou devoirs scolaires","Perd beaucoup de temps à chercher des choses","Panique si des gens ont changé des choses de place","Les parents et/ou les enseignants font remarquer qu'il a perdu des choses"]},
  { id:"A8", q:"Vous laissez-vous facilement distraire par des stimuli externes ?",
    adult:["Du mal à ignorer des stimuli externes","Du mal à reprendre les choses après avoir été distrait","Facilement distrait par des bruits ou des événements","Facilement distrait par une conversation entre d'autres personnes","Du mal à filtrer et/ou sélectionner des informations"],
    child:["En classe, il regarde souvent dehors","Facilement distrait par des bruits ou des événements","Du mal à reprendre les choses après avoir été distrait"]},
  { id:"A9", q:"Avez-vous des oublis fréquents dans la vie quotidienne ?",
    adult:["Oublie des rendez-vous ou des obligations","Oublie les clés, l'agenda, etc.","A besoin de rappels fréquents concernant les rendez-vous","Retourne sur ses pas pour prendre des choses oubliées","Utilise des programmes rigides pour être sûr de ne rien oublier","Ne tient pas à jour son agenda et/ou oublie de consulter son agenda"],
    child:["Oublie des rendez-vous ou des consignes","On doit souvent lui rappeler les choses","S'arrête en chemin parce qu'il a oublié ce qu'il devait faire","Oublie d'apporter des affaires scolaires","Oublie des choses à l'école ou chez des amis"]},
];

export const HYPERACTIVITY = [
  { id:"HI1", q:"Remuez-vous souvent les mains ou les pieds, ou vous tortillez-vous souvent sur votre siège ?",
    adult:["Du mal à rester assis immobile","Remue les jambes","Tape avec un stylo ou joue avec un objet","Tortille les cheveux ou ronge les ongles","Capable de contrôler l'agitation mais cela vous stresse"],
    child:["Les parents disent souvent « tiens-toi tranquille »","Remue les jambes","Tape avec un stylo ou joue avec un objet","Tortille les cheveux ou ronge les ongles","Incapable de rester assis de façon relaxée","Capable de contrôler l'agitation mais cela vous stressait"]},
  { id:"HI2", q:"Vous levez-vous souvent dans des situations où vous êtes supposé rester assis ?",
    adult:["Évite les réunions, les conférences, les cérémonies religieuses, etc.","Préfère marcher plutôt que rester assis","Ne reste jamais longtemps assis tranquille, bouge sans cesse","Stressé par l'obligation de rester assis","Trouve une excuse pour pouvoir marcher"],
    child:["Se lève souvent pendant les repas ou en classe","Trouve très difficile de rester assis en classe ou pendant les repas","On lui dit souvent de rester assis","Trouve une excuse pour pouvoir marcher"]},
  { id:"HI3", q:"Vous sentez-vous souvent agité(e) ?",
    adult:["Se sent agité ou nerveux à l'intérieur","Ressent constamment le sentiment d'avoir quelque chose à faire","Trouve difficile de se relaxer"],
    child:["Court toujours","Grimpe sur les meubles ou saute sur les fauteuils","Monte aux arbres","Se sent agité à l'intérieur"]},
  { id:"HI4", q:"Trouvez-vous souvent difficile de profiter d'un moment de détente ?",
    adult:["Parle lorsque cela n'est pas approprié","Se met rapidement en avant en public","Bruyant dans tout type de situations","Du mal à faire des activités tranquillement","Du mal à parler doucement"],
    child:["Fait du bruit en jouant ou en classe","Incapable de regarder la TV ou un film tranquillement","On lui demande souvent de se calmer ou d'être plus tranquille","Se met rapidement en avant en public"]},
  { id:"HI5", q:"Êtes-vous souvent « sur la brèche » ou comme si vous étiez « dirigé(e) par un moteur » ?",
    adult:["Toujours occupé à faire quelque chose","Déborde d'énergie, toujours en mouvement","Franchit ses propres limites","Lâche difficilement prise, excessivement insistant"],
    child:["Constamment occupé","Remarqué par son activité en classe ou à la maison","Déborde d'énergie","Toujours sur la brèche, monté sur ressorts"]},
  { id:"HI6", q:"Parlez-vous souvent trop ?",
    adult:["Parle tellement que les gens trouvent cela fatiguant","Connu pour parler de manière incessante","Trouve difficile d'arrêter de parler","Tendance à trop parler","Ne laisse pas l'occasion aux autres d'intervenir dans une conversation","Besoin de beaucoup de mots pour dire quelque chose"],
    child:["Connu comme une « boîte à paroles »","Les enfants ou les enseignants demandent souvent le silence","Les fiches scolaires mentionnent souvent des bavardages","Puni pour avoir trop parlé","Gêne le travail scolaire des autres en parlant trop","Ne laisse pas les autres parler dans une conversation"]},
  { id:"HI7", q:"Laissez-vous souvent échapper la réponse à une question qui n'est pas encore entièrement posée ?",
    adult:["Dit ce qu'il pense","Dit les choses sans réfléchir","Donne des réponses avant que les gens aient fini de parler","Finit les phrases des autres","Manque de tact"],
    child:["Dit les choses sans réfléchir","Veut être le premier à répondre aux questions en classe","Donne la première réponse qui lui vient à l'esprit","Interrompt les autres avant que les phrases soient finies","Blesse verbalement (manque de tact)"]},
  { id:"HI8", q:"Trouvez-vous souvent difficile d'attendre votre tour ?",
    adult:["Difficulté à attendre dans une file, veut doubler","Du mal à attendre patiemment dans la circulation","Du mal à attendre son tour dans les conversations","Impatient","Rapidement commence ou met terme à des relations ou des emplois par impatience"],
    child:["Du mal à attendre son tour dans les sports ou les jeux","Du mal à attendre son tour en classe","Toujours le premier à parler ou agir","Rapidement impatient","Traverse la route sans regarder"]},
  { id:"HI9", q:"Interrompez-vous souvent les autres ou imposez-vous votre présence ?",
    adult:["Rapide à interférer avec les autres","Interrompt les autres","Dérange sans qu'on lui ait rien demandé","Les autres font remarquer qu'il est intrusif","Du mal à respecter les limites des autres","A une opinion sur tout et la donne immédiatement"],
    child:["S'immisce dans les jeux des autres","Interrompt les conversations des autres","Réagit sur tout","Incapable d'attendre"]},
];

export const IMPAIRMENT = {
  adult: {
    work:      { label:"Travail / Éducation", items:["N'a pas atteint le niveau d'étude pour le travail voulu","Travaille en deçà du niveau d'étude","Rapidement fatigué d'un lieu de travail","Succession de plusieurs emplois à court terme","Difficulté avec le travail administratif/la planification","N'obtient pas de promotions","Sous-performant au travail","A quitté un emploi ou a été renvoyé après une dispute","Arrêts de travail ou invalidité liés aux symptômes","Retentissement limité par compensation par un fort niveau intellectuel","Retentissement limité par compensation par la structure externe"]},
    relations: { label:"Relations et/ou Famille", items:["Rapidement fatigué par les relations","Débute/termine impulsivement les relations","Compensation nécessaire des symptômes par le conjoint","Problèmes relationnels, nombreuses disputes, manque d'intimité","Divorce à cause des symptômes","Problèmes sexuels à cause des symptômes","Problèmes avec l'éducation à cause des symptômes","Difficultés ménagères et/ou administratives","Problèmes financiers ou jeux d'argent","N'ose pas commencer une relation"]},
    social:    { label:"Contacts sociaux", items:["Rapidement fatigué par les contacts sociaux","Difficulté à maintenir des contacts sociaux","Conflits résultant de problèmes de communication","Difficulté à initier des contacts sociaux","Faible auto-affirmation de soi","Inattention (oubli d'envoyer une carte, d'être empathique, etc.)"]},
    leisure:   { label:"Temps libre / Hobby", items:["Incapable de se relaxer complètement pendant le temps libre","Obligé de pratiquer beaucoup de sport pour se relaxer","Blessures à la suite d'une pratique excessive du sport","Incapable de terminer un livre ou de regarder un film jusqu'au bout","Fatigué parce qu'affairé en permanence","Rapidement lassé par les hobbies","Accidents ou suspension de permis de conduire","Recherche de sensations et/ou prise trop fréquente de risques","Problèmes avec la police/la justice","Hyperphagie"]},
    self:      { label:"Confiance en soi / Image de soi", items:["Doute de lui-même suite aux remarques négatives des autres","Image de soi négative à cause des échecs du passé","Peur de l'échec en commençant de nouvelles choses","Réaction excessive aux critiques","Perfectionnisme","Affecté par les symptômes du TDAH"]},
  },
  child: {
    education: { label:"Éducation", items:["Niveau d'études inférieur à celui prédit par le QI","Redoublement à cause de problèmes de concentration","Études inachevées / Renvoi d'un établissement scolaire","Plus d'années pour terminer les études que nécessaire","A obtenu un niveau d'étude conforme au QI mais avec beaucoup de difficultés","Difficulté à faire les devoirs","Éducation spéciale à cause des symptômes","Commentaires des enseignants sur le comportement ou la concentration","Retentissement limité par compensation par un fort niveau intellectuel","Retentissement limité par compensation par la structure externe"]},
    family:    { label:"Famille", items:["Disputes fréquentes avec frères et sœurs","Punitions ou corrections fréquentes","Peu de contacts avec la famille à cause des conflits","A nécessité le soutien des parents pour une période plus longue que la normale"]},
    social:    { label:"Contacts sociaux", items:["Difficulté à maintenir des contacts sociaux","Conflits résultant de problèmes de communication","Difficulté à initier des contacts sociaux","Faible auto-affirmation de soi","Peu d'amis","Taquiné par les autres","Exclu du groupe ou n'est pas invité à participer aux activités","Joue les petits durs"]},
    leisure:   { label:"Temps libre / Hobby", items:["Incapable de se relaxer correctement pendant le temps libre","Obligé de pratiquer beaucoup de sport pour se relaxer","Blessures à la suite d'une pratique excessive du sport","Incapable de terminer un livre ou de regarder un film jusqu'au bout","Fatigué parce qu'affairé en permanence","Rapidement lassé par les hobbies","Recherche de sensations et/ou prise trop fréquente de risques","Problèmes avec la police/la justice","Nombre augmenté d'accidents"]},
    self:      { label:"Confiance en soi / Image de soi", items:["Doute de lui-même suite aux remarques négatives des autres","Image de soi négative à cause des échecs du passé","Peur de l'échec avant de démarrer de nouvelles choses","Réaction excessive aux critiques","Perfectionnisme"]},
  },
};
